Webserver PKCS11 Examples
Nitrokey/nethsm-pkcs11 pull request #149
Opened 2023-11-30 15:10 UTC by q-nk

Updating the web server example scripts to the new NetHSM API.

2023-12-01 08:58 UTC, jans23 commented
Has [this feedback](https://github.com/Nitrokey/nethsm-pkcs11/pull/50#issuecomment-1831259458) been considered?

2023-12-01 16:56 UTC, mmerklinger requested changes

2023-12-01 16:56 UTC, mmerklinger commented on container/apache/p11nethsm.conf
>        - url: "https://192.168.178.177:8443/api/v1"
Please update this line to `- url: "https://localhost:8443/api/v1"` to keep it consistent with the value of `HOST` in the generate script.

2023-12-01 16:56 UTC, mmerklinger commented on container/nginx/p11nethsm.conf
>        - url: "https://192.168.3.161:8443/api/v1"
Please update this line to `- url: "https://localhost:8443/api/v1"` to keep it consistent with the value of `HOST` in the generate script.

2023-12-01 17:04 UTC, mmerklinger commented
> Has [this feedback](https://github.com/Nitrokey/nethsm-pkcs11/pull/50#issuecomment-1831259458) been considered?

No, the key is still generated locally and upload to the NetHSM. It depends what we want to show with the example.
@jans23 Do you want to have the safer example and the key generated on the NetHSM?

2023-12-04 13:52 UTC, mmerklinger commented
@q-nk Please implement the changes to generate the key on the NetHSM.

2023-12-08 13:51 UTC, merged